import type { ComponentType } from "react";

/**
 * Static MDX import map (decision D-14). Keys are `<moduleId>/<lessonId>.mdx`
 * — matching each lesson JSON's contentPath suffix. The bundler compiles
 * content MDX at build time; no runtime compilation.
 *
 * GENERATED by scripts/generate-mdx-map.mjs — do not edit by hand.
 * Regenerate with `pnpm content:map` (runs automatically prebuild/predev).
 */
export type MdxComponent = ComponentType<Record<string, unknown>>;

import AnatomyOfAWebsite from "@/content/tracks/web-development/courses/web-development-beginner/modules/the-web-and-your-first-website/lessons/anatomy-of-a-website.mdx";
import HowTheWebWorks from "@/content/tracks/web-development/courses/web-development-beginner/modules/the-web-and-your-first-website/lessons/how-the-web-works.mdx";
import HtmlAttributes from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-attributes.mdx";
import HtmlCheckpoint from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-checkpoint.mdx";
import HtmlElements from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-elements.mdx";
import HtmlForms from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-forms.mdx";
import HtmlImages from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-images.mdx";
import HtmlLinks from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-links.mdx";
import HtmlListsAndTables from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-lists-and-tables.mdx";
import HtmlSemantics from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/html-semantics.mdx";
import InspectingWithDevtools from "@/content/tracks/web-development/courses/web-development-beginner/modules/the-web-and-your-first-website/lessons/inspecting-with-devtools.mdx";
import IntroductionToHtml from "@/content/tracks/web-development/courses/web-development-beginner/modules/html-foundations/lessons/introduction-to-html.mdx";
import YourFirstHtmlPage from "@/content/tracks/web-development/courses/web-development-beginner/modules/the-web-and-your-first-website/lessons/your-first-html-page.mdx";

export const mdxMap: Record<string, MdxComponent> = {
  ["html-foundations/introduction-to-html.mdx"]: IntroductionToHtml,
  ["html-foundations/html-elements.mdx"]: HtmlElements,
  ["html-foundations/html-attributes.mdx"]: HtmlAttributes,
  ["html-foundations/html-links.mdx"]: HtmlLinks,
  ["html-foundations/html-images.mdx"]: HtmlImages,
  ["html-foundations/html-lists-and-tables.mdx"]: HtmlListsAndTables,
  ["html-foundations/html-semantics.mdx"]: HtmlSemantics,
  ["html-foundations/html-forms.mdx"]: HtmlForms,
  ["html-foundations/html-checkpoint.mdx"]: HtmlCheckpoint,
  ["the-web-and-your-first-website/how-the-web-works.mdx"]: HowTheWebWorks,
  ["the-web-and-your-first-website/anatomy-of-a-website.mdx"]: AnatomyOfAWebsite,
  ["the-web-and-your-first-website/your-first-html-page.mdx"]: YourFirstHtmlPage,
  ["the-web-and-your-first-website/inspecting-with-devtools.mdx"]: InspectingWithDevtools,
};

export function getLessonMdx(contentPath: string): MdxComponent | undefined {
  // contentPath is "./<lessonId>.mdx" relative to the lesson JSON; the map
  // key is "<moduleId>/<lessonId>.mdx". Fall back to the bare filename for
  // legacy single-module content.
  const normalized = contentPath.replace(/^\.\//, "");
  if (mdxMap[normalized]) return mdxMap[normalized];
  const fileName = normalized.split("/").pop() ?? normalized;
  return mdxMap[Object.keys(mdxMap).find((key) => key.endsWith("/" + fileName)) ?? ""];
}
