#!/usr/bin/env python3
"""AP CSA Core — course manifest + track registration (additive)."""
from apcc import write_course

write_course(
    "AP CSA Core & Exam Preparation",
    "The bridge from knowing Java to solving AP CSA problems: tracing mastery, specification-driven implementation, the four FRQ types, MCQ strategy and error clinics, timed practice, and a full exam simulation — aligned to the revised (Fall 2025) AP CSA framework.",
    "Students who finished AP CSA Foundations (or know core Java) and want exam performance: reliable AP-style problem solving, code tracing under pressure, FRQ methodology, and timed practice before moving to full mock exams.",
    [
        "Trace unfamiliar Java programs with state tables, frames, and dispatch reasoning",
        "Implement methods and classes directly from specifications, honoring preconditions and edge cases",
        "Solve the exam's four FRQ types with the eight-step workflow and partial-credit strategy",
        "Apply MCQ strategy: prediction-first answering, trap recognition, and probe-based elimination",
        "Master arrays, ArrayList, 2D arrays, strings, inheritance, and recursion at AP problem depth",
        "Debug broken solutions by locating the first contract divergence and repairing minimally",
        "Work at exam tempo with the two-pass sweep, post-set audits, and full simulations",
        "Self-score against rubric behavior and target the biggest remaining loss",
    ],
    "AP CSA Core & Luyện thi",
    "Cây cầu từ biết Java đến giải được bài AP CSA: làm chủ truy vết, hiện thực theo đặc tả, bốn dạng FRQ, chiến lược MCQ và phòng sửa lỗi, luyện có giờ, và một buổi mô phỏng thi — bám sát khung AP CSA sửa đổi (Thu 2025).",
    "Học sinh đã hoàn thành AP CSA Foundations (hoặc nắm Java cốt lõi) và muốn đạt hiệu năng phòng thi: giải bài kiểu AP đáng tin, truy vết mã dưới áp lực, phương pháp FRQ, và luyện có giờ trước khi chuyển sang đề mô phỏng hoàn chỉnh.",
    [
        "Truy vết chương trình Java lạ bằng bảng trạng thái, khung gọi, và suy luận điều phối",
        "Hiện thực phương thức và lớp trực tiếp từ đặc tả, tôn trọng điều kiện tiên quyết và trường hợp biên",
        "Giải bốn dạng FRQ của đề bằng quy trình tám bước và chiến lược điểm một phần",
        "Áp dụng chiến lược MCQ: trả lời dự-đoán-trước, nhận diện bẫy, và loại trừ bằng phép dò",
        "Làm chủ mảng, ArrayList, mảng 2 chiều, chuỗi, kế thừa, và đệ quy ở độ sâu bài-tập AP",
        "Gỡ lỗi lời giải bằng cách định vị điểm-lệch-hợp-đồng đầu tiên và sửa tối thiểu",
        "Làm việc theo nhịp thi với quét-hai-lượt, kiểm sát sau bộ, và mô phỏng toàn diện",
        "Tự chấm theo hành vi rubric và nhắm vào mất-mát lớn còn lại",
    ],
    [
        "cx-bootcamp",
        "cx-tracing",
        "cx-flow",
        "cx-specs",
        "cx-strings",
        "cx-arrays",
        "cx-arraylist",
        "cx-2d",
        "cx-objects",
        "cx-inheritance",
        "cx-recursion",
        "cx-mixed",
        "cx-mcq",
        "cx-frq-fund",
        "cx-frq-class",
        "cx-frq-list",
        "cx-frq-2d",
        "cx-frq-debug",
        "cx-timed",
        "cx-sim",
    ],
)
