# VI metadata overlays: modules, practices, lessons (title/description)
# ids -> (vi_title, vi_description)
VI_MODULES = {
    "csa-language-semantics": ("Ngữ nghĩa ngôn ngữ nâng cao", "Mô hình thực thi, hành vi value vs reference, boxing, null-state, và cách compiler resolve mã của bạn."),
    "csa-memory-object-model": ("Bộ nhớ và mô hình đối tượng", "Giá trị nằm ở đâu, sao chép khi nào, span tránh cấp phát ra sao, và cách đo tất cả chúng."),
    "csa-generics-deep": ("Generics và hệ thống kiểu nâng cao", "Variance, static abstract, generic math, và các ràng buộc biên dịch thành chứng minh — cùng chi phí runtime của chúng."),
    "csa-delegates-closures": ("Delegate, Closure, và C# hàm số", "Delegate thực chất là gì, lambda cấp phát gì, closure bắt gì, và khi nào expression tree thắng code."),
    "csa-reflection-attributes": ("Reflection và Attribute", "Khám phá kiểu, gọi động, cache metadata, hành vi dẫn dắt bởi attribute — và hóa đơn bảo mật lẫn hiệu năng."),
    "csa-roslyn": ("Roslyn và Compiler API", "Cây cú pháp, mô hình ngữ nghĩa, symbol, diagnostic — và các analyzer đọc mã của bạn như compiler."),
    "csa-source-generators": ("Source Generator", "Sinh mã lúc biên dịch: pipeline tăng dần, luật mã sinh ra, và tương lai không reflection."),
    "csa-expression-trees": ("Expression Tree và LINQ Provider", "Dựng, biên dịch, kiểm tra, và dịch cây biểu thức — cỗ máy dưới mọi LINQ provider."),
    "csa-async-deep": ("Async nâng cao", "State machine, ValueTask, lan truyền hủy, async stream, và các mode lỗi mà async che giấu."),
    "csa-concurrency": ("Concurrency nâng cao", "Khả kiến bộ nhớ, Interlocked, collection đồng thời, deadlock — và các bug chỉ xuất hiện dưới tải."),
    "csa-parallel": ("Lập trình song song", "Parallel.For, PLINQ, partitioning, và phép toán khi nào song song hoá đáng giá — đo đạc, không suy diễn."),
    "csa-channels": ("Channel và hệ thống Producer/Consumer", "System.Threading.Channels: buffer có giới hạn, backpressure, hoàn thành, và pipeline tắt lịch sự."),
    "csa-gc": ("Garbage Collection và quản lý bộ nhớ", "Thế hệ, hành vi cấp phát, finalization, weak reference, rò rỉ, và pooling — đo đạc, không tin truyền miệng."),
    "csa-performance": ("Kỹ thuật hiệu năng", "Kỷ luật đo đạc, profile cấp phát và CPU, hiệu ứng JIT, và vòng lặp tối ưu cái đáng tối ưu."),
    "csa-clr-internals": ("JIT, Runtime, và CLR Internals", "Từ IL đến mã máy: assembly, metadata, tiered compilation, dispatch ảo, và exception."),
    "csa-diagnostics": ("Gỡ lỗi và chẩn đoán nâng cao", "Đọc lỗi: stack trace, phân tích exception, health probe, và mẫu resilience — với công cụ sandbox có."),
    "csa-unsafe-interop": ("Native Interop và Unsafe C#", "Con trỏ trong managed memory, pinning, khái niệm P/Invoke, blittable type — ranh giới managed/unmanaged, dạy an toàn."),
    "csa-aot-deployment": ("NativeAOT, Trimming, và mô hình triển khai", ".NET giao hàng thế nào: framework-dependent, self-contained, trimmed, AOT — các đánh đổi và thuế reflection."),
    "csa-networking": ("Networking nâng cao", "Socket trên loopback: framing, giao thức, vòng đời kết nối, và mode lỗi của I/O phân tán — xác minh trong sandbox."),
    "csa-distributed": ("Hệ thống phân tán", "Thất bại, retry, idempotency, nhất quán cuối cùng — khái niệm và mô phỏng, tất định trong sandbox."),
    "csa-security": ("Bảo mật nâng cao", "Kỷ luật crypto API, xử lý secret, phòng thủ injection và deserialization — threat modeling cho dịch vụ C#."),
    "csa-data-access": ("Truy cập dữ liệu nâng cao", "Vòng đời kết nối, an toàn transaction, mức isolation, concurrency lạc quan, và N+1 — mô phỏng trong hộp, tất định."),
    "csa-capstone": ("Kiến trúc sản xuất và Capstone", "Modular monolith, hướng phụ thuộc, quan sát được, resilience — và một nền tảng xử lý job lắp ráp tất cả."),
}

VI_PRACTICES = {
    "csa-p1-semantics": ("Ngữ nghĩa dưới kính hiển vi", "Bài tập dự đoán-và-xác minh: bản sao, box, null-state, và bẫy resolution."),
    "csa-p2-memory": ("Bài tập bộ nhớ", "Span, bản sao phòng thủ, ref return, và đo cấp phát trung thực."),
    "csa-p3-generics": ("Cỗ máy generic", "Bài variance, trừu tượng static-abstract, và suy luận cấp phát cho mã generic."),
    "csa-p4-delegates": ("Bài delegate", "Method group vs lambda, phân tích capture, hợp thành delegate, và một mini rule engine."),
    "csa-p5-reflection": ("Bài reflection", "Khám phá, gọi có cache, xác thực dẫn dắt bởi attribute, và bẫy reflection."),
    "csa-p6-roslyn": ("Bài Roslyn", "Đi bộ cú pháp, resolve ngữ nghĩa, phân tích diagnostic, và biên dịch trong tiến trình."),
    "csa-p7-generators": ("Bài generator", "Dựng pipeline, hợp đồng mã sinh ra, diagnostic generator, và xác minh biên dịch."),
    "csa-p8-expressions": ("Bài biểu thức", "Visitor, gấp hằng số, một mini provider, và bẫy compile-mỗi-lần-gọi."),
    "csa-p9-async": ("Bài async", "Suy luận state machine, link hủy, async stream, và kỷ luật async-disposal."),
    "csa-p10-conc": ("Bài concurrency", "Demo khả kiến, phép toán Interlocked, lựa chọn collection đồng thời, và xử triệt mode lỗi."),
    "csa-p11-par": ("Bài song song", "Gộp theo trạng thái cục bộ, thứ tự PLINQ, suy luận Amdahl, và hủy vòng lặp dài."),
    "csa-p12-ch": ("Bài channel", "Backpressure có giới hạn, xả khi tắt, fan-out worker, và ngữ nghĩa hoàn thành."),
    "csa-p13-gc": ("Bài GC", "Profile cấp phát, chi phí finalizer, chẩn đoán rò rỉ event, và quyết định pooling."),
    "csa-p14-perf": ("Bài hiệu năng", "Kỷ luật baseline, săn cấp phát, artefact JIT, và bằng chứng trước/sau."),
    "csa-p15-clr": ("Bài CLR internals", "Kiểm tra assembly, suy luận tiered-JIT, đo chi phí dispatch, và sự thật chi phí exception."),
    "csa-p16-diag": ("Bài chẩn đoán", "Đọc trace, máy trạng thái circuit-breaker, phép toán retry backoff, và ngữ nghĩa health-probe."),
    "csa-p17-unsafe": ("Bài unsafe", "Pinning có giới hạn, diễn giải lại struct, và suy luận an toàn khiến mã unsafe bảo vệ được."),
    "csa-p18-aot": ("Bài triển khai", "Suy luận trim-safety, kiểm toán tính năng động, và phép toán chi phí khởi động."),
    "csa-p19-net": ("Bài networking", "Quản lý buffer, máy trạng thái giao thức, thi hành timeout, và xử lý ghi một phần."),
    "csa-p20-dist": ("Bài phân tán", "Retry storm, hợp đồng backpressure, và suy luận nhất quán dưới lỗi mô phỏng."),
    "csa-p21-sec": ("Bài bảo mật", "So sánh an toàn thời gian, phòng thủ path traversal, tư thế deserialization, và suy luận vòng đời token."),
    "csa-p22-data": ("Bài truy cập dữ liệu", "Phép toán ngân sách kết nối, anomaly isolation, và đếm truy vấn N+1 — tất cả tất định."),
    "csa-p24-production": ("Bài sản xuất", "Phép toán capacity, ngân sách lỗi SLO, và luật thăng cấp DLQ — bảng quyết định tất định."),
}

# lesson id -> (vi_title, vi_description)
VI_LESSONS = {
    "csa-m1-execution-model": ("Từ source đến IL đang chạy", "Biên dịch, assembly, metadata, và pipeline JIT — điều thực sự xảy ra trước khi mã của bạn chạy."),
    "csa-m1-value-reference": ("Ngữ nghĩa giá trị vs ngữ nghĩa tham chiếu", "Hành vi sao chép, gán, đẳng thức, và vì sao hai struct không bao giờ là cùng một đối tượng."),
    "csa-m1-boxing": ("Boxing, unboxing, và cấp phát ẩn", "Nơi giá trị lặng lẽ sang heap: interface, API không generic, struct trong delegate."),
    "csa-m1-null-state": ("Phân tích null-state và hợp đồng nullable", "Nullability theo luồng, attribute định hình cảnh báo, và chi phí của việc giả vờ null không xảy ra."),
    "csa-m1-resolution": ("Overload resolution, chuyển đổi, và pattern", "Compiler chọn thành viên thế nào: luật betterness, chuyển đổi do người dùng định nghĩa, cơ chế pattern matching."),
    "csa-checkpoint-m1": ("Checkpoint: ngữ nghĩa ngôn ngữ", "Tổng hợp: dự đoán hành vi compiler và runtime qua các bẫy của module."),
    "csa-m2-layout": ("Stack, heap, và layout đối tượng", "Dữ liệu nằm ở đâu, một object header tốn gì, và đâu là bảo đảm ngôn ngữ vs chi tiết runtime."),
    "csa-m2-ref-returns": ("Ref local, ref return, và bản sao phòng thủ", "Bí danh thay bản sao: ref local/return, ref readonly, và khi nào compiler chèn bản sao dù bạn không muốn."),
    "csa-m2-spans": ("Span<T>, ReadOnlySpan<T>, và stackalloc", "Cửa sổ an toàn vào bộ nhớ: span, luật ref-struct của nó, và stackalloc cho buffer nhỏ."),
    "csa-m2-allocation-measure": ("Đo cấp phát một cách trung thực", "GC.GetAllocatedBytesForCurrentThread, warmup JIT, và vì sao một lần đo là nói dối."),
    "csa-checkpoint-m2": ("Checkpoint: mô hình bộ nhớ", "Tổng hợp: quyết định sao chép/bí danh, cắt span, và một ngân sách cấp phát được đo."),
    "csa-m3-variance": ("Variance: co, contra, in", "Vì sao IEnumerable<T> là out, Action<in T> là in, IList<T> không cái nào — và điều đó mua được gì."),
    "csa-m3-static-abstracts": ("Thành viên static abstract và generic math", "Interface với static abstract: tham số kiểu trở thành đích dispatch đa hình."),
    "csa-m3-generics-runtime": ("Generics tốn gì lúc chạy", "Chia sẻ mã cho reference type, chuyên biệt hoá cho value type, và nơi điều đó lộ diện."),
    "csa-checkpoint-m3": ("Checkpoint: generics", "Tổng hợp: tính hợp lệ variance, dispatch static-abstract, và suy luận cấp phát generic."),
    "csa-m4-delegate-machine": ("Cỗ máy delegate", "Đối tượng delegate, method group, danh sách gọi, và mỗi lambda biên dịch thành gì."),
    "csa-m4-closures": ("Closure và biến bị bắt", "Display class, vòng đời capture, bản sửa biến vòng lặp, và chi phí cấp phát closure."),
    "csa-m4-expr-vs-delegate": ("Expression tree vs delegate", "Code thành data: khi nào biên dịch ra IL, khi nào kiểm tra, và đường chi phí giữa chúng."),
    "csa-checkpoint-m4": ("Checkpoint: delegate và closure", "Tổng hợp: ngữ nghĩa capture và số đếm cấp phát dưới phép đo."),
    "csa-m5-discovery": ("Type, MemberInfo, và khám phá", "Đi bộ assembly và kiểu lúc chạy: các bảng metadata thực sự tốn bao nhiêu để đọc."),
    "csa-m5-invocation": ("Gọi động và hóa đơn của nó", "MethodInfo.Invoke vs delegate có cache vs biểu thức biên dịch — đo được, không tin truyền miệng."),
    "csa-m5-attributes": ("Attribute là metadata thực thi được", "Attribute tùy chỉnh, đích, kế thừa, truy xuất, và dựng hành vi dẫn dắt bởi attribute."),
    "csa-m5-security": ("Reflection và bảo mật", "Vì sao reflection đánh bại phân tích tĩnh, nó lộ gì, và kỷ luật giữ nó an toàn."),
    "csa-checkpoint-m5": ("Checkpoint: reflection", "Tổng hợp: bộ nạp plugin có cache với cấu hình dẫn dắt bởi attribute."),
    "csa-m6-roslyn-architecture": ("Hai góc nhìn của Roslyn về mã nguồn", "SyntaxTree vs SemanticModel: cây xanh/đỏ, symbol, và vì sao sự tách biệt cho phép IDE tồn tại."),
    "csa-m6-analyzers": ("Viết analyzer và diagnostic", "Kiến trúc analyzer, diagnostic descriptor, đăng ký tăng dần, và sửa thay vì chỉ báo lỗi."),
    "csa-m6-compilation-api": ("Compilation API", "CSharpCompilation từ đầu đến cuối: reference, diagnostic, phát assembly — ngay trong sandbox này."),
    "csa-checkpoint-m6": ("Checkpoint: Roslyn", "Tổng hợp: đi bộ cú pháp, resolve symbol, và điều khiển một compilation bằng chương trình."),
    "csa-m7-generator-model": ("Mô hình source generator", "Generator là gì, chạy khi nào, làm và không làm được gì — và vì sao 'compile-time' đổi thiết kế."),
    "csa-m7-incremental": ("Generator tăng dần", "Pipeline IIncrementalGenerator: cache, đẳng thức, và không chạy lại cả thế giới cho mỗi phím."),
    "csa-m7-generated-code": ("Luật của mã sinh ra", "Mã sinh ra phải đủ đường dẫn, biên dịch sạch, và gỡ được — các hợp đồng giữ generator hữu ích."),
    "csa-checkpoint-m7": ("Checkpoint: source generator", "Tổng hợp: điều khiển generator bằng chương trình và xác minh output của nó biên dịch được."),
    "csa-m8-tree-anatomy": ("Giải phẫu một expression tree", "Node, visitor, reduction, và một lambda expression thực sự trở thành data gì."),
    "csa-m8-building": ("Dựng và biên dịch biểu thức", "Expression.Parameter, MakeBinary, Lambda, Compile — dựng code mà compiler chưa từng thấy."),
    "csa-m8-visitors": ("Duyệt và viết lại cây", "ExpressionVisitor là bộ chuyển đổi phổ quát: điều EF làm với predicate của bạn."),
    "csa-checkpoint-m8": ("Checkpoint: expression tree", "Tổng hợp: dựng, chuyển đổi, và đánh giá một pipeline predicate."),
    "csa-m9-state-machine": ("Máy trạng thái async", "Await biên dịch thành gì: builder, MoveNext, đường nóng vs lạnh — với một bản decompile thật."),
    "csa-m9-valuetask": ("ValueTask: khi nào và vì sao", "Fast path không cấp phát, hai luật hợp đồng của nó, và các bug nó mở ra khi dùng sai."),
    "csa-m9-cancellation": ("Hủy hoạt động thật sự", "Token, link, đăng ký, timeout — và vì sao hủy hợp tác thất bại lặng lẽ."),
    "csa-m9-async-streams": ("Async stream và IAsyncDisposable", "Pipeline IAsyncEnumerable, await using, và backpressure giữa producer/consumer async."),
    "csa-checkpoint-m9": ("Checkpoint: async", "Tổng hợp: kỷ luật ValueTask và đúng đắn hủy dưới thực thi thật."),
    "csa-m10-visibility": ("Khả kiến bộ nhớ và thứ tự", "Vì sao cờ bool nói dối: cache, xếp lại thứ tự của compiler, Volatile, Interlocked — runtime thực sự bảo đảm gì."),
    "csa-m10-locks": ("Khóa, Monitor, và chi phí của chúng", "Bên trong Monitor, tranh chấp khóa, ReaderWriterLockSlim, SemaphoreSlim — và khi nào khóa là công cụ sai."),
    "csa-m10-concurrent-collections": ("Collection đồng thời bên trong", "Phân đoạn ConcurrentDictionary và luật atomicity, segment của ConcurrentQueue, và khi nào khóa thuần thắng."),
    "csa-m10-failure-modes": ("Race condition, deadlock, starvation", "Danh mục lỗi kinh điển: mỗi cái phát sinh thế nào, biểu hiện trong sản xuất ra sao, chẩn đoán bằng cách nào."),
    "csa-checkpoint-m10": ("Checkpoint: concurrency", "Tổng hợp: sửa một race sống bằng atomic và suy luận về một deadlock thật."),
    "csa-m11-data-parallel": ("Song song dữ liệu: Parallel.For và bạn bè", "Parallel.For/ForEach, trạng thái cục bộ, stop/break, và scheduler chia công việc qua các core thế nào."),
    "csa-m11-plinq": ("PLINQ: truy vấn song song, chi phí thật", "AsParallel, thứ tự, gộp kết quả, mức song song — và những workload mà PLINQ thua LINQ."),
    "csa-m11-when-parallel": ("Khi nào song song hoá đáng giá — phép toán", "Định luật Amdahl, chi phí mỗi phần tử, chia chunk, false sharing — mô hình bạn dùng TRƯỚC khi viết vòng lặp."),
    "csa-m11-parallel-pitfalls": ("Bẫy song song và xử lý exception", "AggregateException, lỗi gộp theo trạng thái cục bộ, oversubscription, và hủy vòng lặp song song."),
    "csa-checkpoint-m11": ("Checkpoint: parallel", "Tổng hợp: một pipeline song song được đo với hủy đúng và gộp đúng."),
    "csa-m12-channel-model": ("Mô hình Channel<T>", "Nửa Reader/Writer, bounded vs unbounded, hành vi khi đầy — vốn từ của backpressure."),
    "csa-m12-backpressure": ("Backpressure như một công cụ thiết kế", "Vì sao bounded channel là mặc định: load shedding, sàn độ trễ, và unbounded queue nuốt bộ nhớ."),
    "csa-m12-completion": ("Hoàn thành và tắt lịch sự", "TryComplete, điểm dừng ReadAllAsync, chiến lược xả, và thứ tự tắt giữa các tầng pipeline."),
    "csa-m12-pipelines": ("Kiến trúc pipeline nhiều tầng", "Ghép kênh theo tầng, fan-out/fan-in, và nơi Channels thắng các bộ sưu tập Task."),
    "csa-checkpoint-m12": ("Checkpoint: channels", "Tổng hợp: dựng producer/consumer có giới hạn với ngữ nghĩa xả-khi-tắt."),
    "csa-m13-generations": ("Thế hệ và cấp phát", "Gen0/1/2, LOH, tốc độ cấp phát, và vì sao cấp phát rẻ là mục tiêu thiết kế, không phải kẻ thù."),
    "csa-m13-lifetime": ("Vòng đời: finalizer, disposal, weak ref", "Chi phí hàng đợi finalizer, mẫu Dispose, weak reference, và rò rỉ event-handler."),
    "csa-m13-pooling": ("Pooling: ArrayPool và bạn bè", "Khi nào pooling đáng giá, ArrayPool bucket hoạt động ra sao, và các bug thuê/trả gây ra."),
    "csa-m13-leaks": ("Rò rỉ bộ nhớ trong ngôn ngữ có GC", "Ngôn ngữ có GC vẫn rò rỉ thế nào: root, event, cache, timer — và cách tìm từng loại."),
    "csa-checkpoint-m13": ("Checkpoint: GC và bộ nhớ", "Tổng hợp: đo cấp phát, chứng minh vòng đời weak-reference, và đếm collection."),
    "csa-m14-measure-first": ("Đo trước: kỷ luật benchmark", "Warmup, số lần lặp, sự trung thực thống kê, và vì sao chiếc đồng hồ bấm giờ đang nói dối bạn."),
    "csa-m14-profiling": ("Profile cấp phát và CPU", "Đọc chênh lệch cấp phát, bộ đếm GC, mẫu CPU thành giả thuyết điểm nghẽn."),
    "csa-m14-jit-effects": ("Hiệu ứng JIT lên phép đo của bạn", "Tiered compilation, inlining, devirtualization, loại bỏ mã chết — và cách mỗi cái làm giả kết quả."),
    "csa-m14-optimization-loop": ("Vòng lặp tối ưu", "MEASURE → PROFILE → CHANGE → MEASURE AGAIN: một tối ưu hoàn chỉnh với bằng chứng trước/sau."),
    "csa-checkpoint-m14": ("Checkpoint: hiệu năng", "Tổng hợp: tối ưu dựa trên baseline được đo và chứng minh thắng bằng con số."),
    "csa-m15-assemblies": ("Assembly, metadata, và IL", "DLL chứa gì, IL mã hoá ý định của bạn thế nào, và loader resolve reference ra sao."),
    "csa-m15-jit": ("JIT và tiered compilation", "Tier 0 → tier 1, OSR, dynamic PGO — .NET thực thi phương thức của bạn lần đầu và lần thứ trăm thế nào."),
    "csa-m15-dispatch": ("Dispatch ảo và gọi interface", "Method table, phân giải dispatch interface, và vì sao `sealed` là một tối ưu thật."),
    "csa-m15-exceptions": ("Exception lúc chạy", "Giải unwinding hai lượt, finally/fault handler, và mô hình chi phí thật của try/catch."),
    "csa-checkpoint-m15": ("Checkpoint: CLR internals", "Tổng hợp: kiểm tra hành vi runtime qua reflection và đo chi phí dispatch."),
    "csa-m16-stack-traces": ("Stack trace là bằng chứng", "Đọc frame MoveNext async, ngữ nghĩa rethrow, inner exception, và trace bị cắt."),
    "csa-m16-failure-forensics": ("Pháp y lỗi không cần debugger", "Log có cấu trúc, correlation, tái tạo tất định, và kỷ luật giả thuyết."),
    "csa-m16-health-resilience": ("Health probe và nguyên mẫu resilience", "Liveness vs readiness, circuit breaker, retry có backoff — tín hiệu runtime giữ hệ thống gỡ được."),
    "csa-m16-checkpoint-lesson": ("Bài checkpoint: chẩn đoán dịch vụ hỏng", "Một ca chẩn đoán trọn vẹn: từ triệu chứng đến nguyên nhân gốc qua bằng chứng, không đoán mò."),
    "csa-m17-boundary": ("Managed, unmanaged, unsafe: ranh giới", "Ba thế giới và luật của chúng — mã unsafe thực sự mở khoá gì, và điều gì nó không bao giờ mở."),
    "csa-m17-pointers": ("Con trỏ unsafe, fixed, và pinning", "Câu lệnh fixed, phép toán con trỏ, và vì sao pinning đối đầu với GC (và cách ngừng đối đầu)."),
    "csa-m17-pin-stories": ("Interop không cần thư viện native: Unsafe, MemoryMarshal", "Unsafe.As, MemoryMarshal.Cast — các mẹo con trỏ trong managed memory không cần P/Invoke."),
    "csa-m17-pinvoke-concepts": ("Khái niệm P/Invoke và hóa đơn bảo mật", "Marshaling, blittable type, function pointer, SafeHandle — và bề mặt tấn công mã unsafe mở ra."),
    "csa-checkpoint-m17": ("Checkpoint: unsafe và interop", "Tổng hợp: phép toán con trỏ trong managed memory, làm an toàn và đo được."),
    "csa-m18-deployment-models": ("Phổ triển khai", "Framework-dependent vs self-contained vs single-file vs ReadyToRun vs NativeAOT — chi phí và hoàn cảnh phù hợp."),
    "csa-m18-trimming": ("Trimming và thuế reflection", "Linker quyết định gì sống sót, vì sao reflection gãy, và các chú thích sửa được."),
    "csa-m18-aot-mindset": ("Tư duy AOT: dịch vụ runtime, một cách tĩnh", "NativeAOT bỏ đi gì (JIT, mã động), đòi hỏi gì (tĩnh mọi thứ), và source generator là cầu nối."),
    "csa-m18-config-concepts": ("Cấu hình, khởi động, và hợp đồng compile-time", "AppContext data, nguồn cấu hình, và biến quyết định runtime thành quyết định compile-time."),
    "csa-checkpoint-m18": ("Checkpoint: triển khai và AOT", "Tổng hợp: suy luận về lựa chọn triển khai và viết reflection an-toàn-trim."),
    "csa-m19-sockets": ("Socket và thế giới loopback", "TcpClient/TcpListener, NetworkStream, và vì sao localhost là phòng thí nghiệm trung thực cho mã giao thức."),
    "csa-m19-framing": ("Framing: bug giao thức đầu tiên", "TCP là luồng byte, không phải luồng thông điệp: length-prefix framing và vì sao 'một ghi = một đọc' là dối."),
    "csa-m19-protocols": ("Thiết kế giao thức: request, response, timeout", "Correlation ID, deadline, và hợp đồng client/server sống sót qua consumer chậm."),
    "csa-m19-failures": ("Mode lỗi mạng trên localhost", "Đọc một phần, slowloris, cạn kết nối, và backpressure — mọi lỗi phân tán, thu nhỏ lại."),
    "csa-checkpoint-m19": ("Checkpoint: networking", "Tổng hợp: hiện thực length-prefix framing và một giao thức echo client/server chạy được."),
    "csa-m20-boundaries": ("Ranh giới dịch vụ và trạng thái phân tán", "Điều gì tạo ranh giới, vì sao lời gọi mạng khác biệt, và các fallacies liên tục sinh ra sự cố."),
    "csa-m20-idempotency": ("Idempotency và exactly-once", "Vì sao exactly-once delivery là dối, và mẫu idempotency-key khiến retry an toàn."),
    "csa-m20-resilience": ("Retry, timeout, và ngân sách thất bại", "Ghép chồng resilience: timeout trong retry trong breaker, với ngân sách thất bại và backoff."),
    "csa-m20-consistency": ("Mô hình nhất quán và trạng thái cuối cùng", "Nhất quán mạnh vs cuối cùng, hội tụ, và cái bẫy đọc-sau-ghi."),
    "csa-checkpoint-m20": ("Checkpoint: hệ phân tán", "Tổng hợp: dựng bộ xử lý tin nhắn idempotent với lỗi mô phỏng."),
    "csa-m21-crypto": ("Dùng đúng API mật mã", "RandomNumberGenerator, băm mật khẩu (PBKDF2), AEAD vs băm thuần — kỷ luật cấp API."),
    "csa-m21-secrets": ("Secret và xử lý token", "Secret sống ở đâu, chúng rò rỉ thế nào, và luật vòng đời cho token và khóa."),
    "csa-m21-injection": ("Injection và deserialization không an toàn", "Cơ chế SQL/command injection, tư thế deserialization an toàn, và path traversal."),
    "csa-m21-threat-model": ("Threat modeling một dịch vụ", "STRIDE-lite trên một API cụ thể: ranh giới tin cậy, rủi ro hàng đầu, và các phòng thủ khóa học đã dạy."),
    "csa-checkpoint-m21": ("Checkpoint: bảo mật", "Tổng hợp: xác minh constant-time, quyết định lưu trữ an toàn, ngăn injection."),
    "csa-m22-connection-lifecycle": ("Vòng đời kết nối và pooling", "Mở muộn, đóng sớm: vì sao kết nối được pool, cạn pool trông ra sao, và các mẫu rò rỉ gây ra nó."),
    "csa-m22-transactions": ("Transaction và mức isolation", "ACID trong thực tế: mỗi mức isolation thực sự ngăn gì, và các anomaly nó để lại."),
    "csa-m22-concurrency": ("Concurrency lạc quan vs bi quan", "Cột phiên bản, cửa sổ xung đột, và vòng retry — vì sao đa số web app nên lạc quan và khi nào thì không."),
    "csa-m22-n-plus-one": ("N+1 và vấn đề hình dạng đọc", "Mẫu truy cập lười nhân số truy vấn thế nào, phát hiện ra sao, và các hình dạng join/batch sửa được."),
    "csa-checkpoint-m22": ("Checkpoint: truy cập dữ liệu", "Tổng hợp: một store concurrency lạc quan với retry và một ngân sách số truy vấn."),
    "csa-m24-architecture": ("Modular monolith và hướng phụ thuộc", "Ranh giới có thể thi hành, thang chi phí của phân tán, và vì sao mũi tên phụ thuộc quyết định kiến trúc."),
    "csa-m24-observability": ("Quan sát được: log, metric, trace", "Log có cấu trúc cho cái gì, metric cho bao nhiêu, trace cho ở đâu — và SLO làm tất cả có ý nghĩa."),
    "csa-m24-reliability": ("Độ tin cậy: retry, idempotency, backpressure", "Bộ xử lý thất bại lắp ráp: timeout trong retry trong breaker, handler idempotent, công việc có giới hạn."),
    "csa-m24-capstone-brief": ("Capstone: nền tảng xử lý job", "Đề bài đầy đủ: API tiếp nhận với idempotency key, hàng đợi có giới hạn, worker retry, DLQ, metric — các mốc và tiêu chí chấm."),
    "csa-checkpoint-m24": ("Checkpoint: kiến trúc sản xuất", "Tổng hợp cuối — tiếp nhận job idempotent, có backpressure, có retry dưới lịch request tất định."),
}
