#!/usr/bin/env python3
"""HSG - Module 6: hsg-sorting (std::sort, comparators, sweep patterns)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from hsg import (
    write_module, write_lesson, write_practice, write_checkpoint,
    challenge, vi_challenge, contest_test,
)

M = "hsg-sorting"
write_module(
    M, "Sorting", "std::sort, custom comparators, and the sort-then-sweep family: min difference, merged intervals, and ranking.",
    "Sắp xếp", "std::sort, comparator tùy chỉnh, và họ \"sắp xếp rồi quét\": hiệu nhỏ nhất, gộp đoạn, và xếp hạng.",
    ["hsg-m6-sort", "hsg-m6-sweep", "hsg-cp-m6"], ["hsg-p6-sorting"],
)
write_lesson(
    M, "hsg-m6-sort", "std::sort and Comparators", "The one sort you need in contests — plus how to write comparators that never break.", 12,
    "## The default sort\n\n```cpp\nint n; in >> n;\nvector<long long> a(n);\nfor (long long& x : a) in >> x;\nsort(a.begin(), a.end());           // ascending, O(n log n)\n```\n\n`std::sort` is **introsort**: quicksort that falls back to heapsort when\nrecursion gets too deep, with an insertion-sort finish on small runs —\nguaranteed O(n log n), no adversarial case. Hand-written bubble/selection\nsort at n = 10^5 is ~10^10 operations: guaranteed TLE. In contests, use\n`std::sort`.\n\n### Descending and stable variants\n\n```cpp\nsort(a.begin(), a.end(), greater<long long>());   // descending\nstable_sort(a.begin(), a.end());                  // keeps equal keys in input order\n```\n\n`stable_sort` matters when you sort by one key and earlier order by another\nmust survive — a classic \"sort by score, ties keep input order\" requirement.\n\n### Custom comparator — the strict-weak-ordering rule\n\n```cpp\nsort(v.begin(), v.end(), [](const pair<int,int>& x, const pair<int,int>& y) {\n    if (x.first != y.first) return x.first < y.first;    // primary key\n    return x.second > y.second;                          // secondary\n});\n```\n\nA comparator must be a **strict weak ordering**: `cmp(x, x)` must be\nfalse, and it must be consistent. The classic bug — `return a <= b;` —\nviolates that (`cmp(x,x)` is true) and is **undefined behavior**: in\npractice it crashes or corrupts the array under `-std=c++20`. Never use\n`<=` or `>=` inside a comparator.",
    "std::sort và comparator", "Bộ sắp duy nhất bạn cần khi thi — và cách viết comparator không bao giờ lỗi.",
    "## Sort mặc định\n\n```cpp\nint n; in >> n;\nvector<long long> a(n);\nfor (long long& x : a) in >> x;\nsort(a.begin(), a.end());           // tăng dần, O(n log n)\n```\n\n`std::sort` là **introsort**: quicksort lùi về heapsort khi đệ quy quá sâu,\nkết thúc bằng insertion sort trên đoạn ngắn — đảm bảo O(n log n), không có\ntrường hợp xấu cố tình phá. Sắp tay kiểu bubble/selection với n = 10^5 là\n~10^10 phép toán: TLE chắc chắn. Khi thi, dùng `std::sort`.\n\n### Giảm dần và biến thể ổn định\n\n```cpp\nsort(a.begin(), a.end(), greater<long long>());   // giảm dần\nstable_sort(a.begin(), a.end());                  // giữ thứ tự nhập của phần tử bằng nhau\n```\n\n`stable_sort` quan trọng khi bạn sắp theo một khóa mà thứ tự trước đó theo\nkhóa khác phải được giữ — kiểu yêu cầu \"sắp theo điểm, hòa giữ thứ tự nhập\".\n\n### Comparator tùy chỉnh — quy tắc sắp thứ tự yếu ngặt\n\n```cpp\nsort(v.begin(), v.end(), [](const pair<int,int>& x, const pair<int,int>& y) {\n    if (x.first != y.first) return x.first < y.first;    // khóa chính\n    return x.second > y.second;                          // khóa phụ\n});\n```\n\nComparator phải là **sắp thứ tự yếu ngặt**: `cmp(x, x)` phải là false và\nphải nhất quán. Lỗi kinh điển — `return a <= b;` — vi phạm quy tắc đó\n(`cmp(x,x)` đúng) và là **hành vi không xác định**: thực tế nó gây crash\nhoặc hỏng mảng dưới `-std=c++20`. Không bao giờ dùng `<=` hay `>=` trong\ncomparator.",
)
write_lesson(
    M, "hsg-m6-sweep", "Sort-Then-Sweep Patterns", "Sorting turns scattered data into neighbors: adjacent differences, merged intervals, and rank assignment.", 13,
    "## Pattern 1 — closest pair by adjacent difference\n\nAfter sorting, the two closest values are **adjacent**:\n\n```cpp\nsort(a.begin(), a.end());\nlong long best = a[1] - a[0];\nfor (int i = 2; i < n; ++i) best = min(best, a[i] - a[i-1]);\n```\n\nO(n^2) pair scanning becomes O(n log n). This \"sorting creates locality\"\nmove powers min-difference, closest-value, and gap problems.\n\n### Pattern 2 — merging intervals\n\nSort by start, then extend the current run:\n\n```cpp\nsort(iv.begin(), iv.end());            // pairs [start, end]\nvector<pair<long long,long long>> merged;\nfor (auto& [s, e] : iv) {\n    if (!merged.empty() && s <= merged.back().second)\n        merged.back().second = max(merged.back().second, e);\n    else merged.push_back({s, e});\n}\n```\n\nWatch `<=` vs `<`: they decide whether touching intervals merge. Read the\nstatement.\n\n### Pattern 3 — rank assignment\n\n```cpp\nsort(b.begin(), b.end());                          // sorted copy\nfor (long long x : a)\n    out << lower_bound(b.begin(), b.end(), x) - b.begin() + 1 << ' ';\n```\n\nEach element's rank = its position in the sorted copy. Ties get distinct\nranks unless you dedupe first — another statement-reading decision.\n\n### Why sorting enables everything else\n\nBinary search (next module), greedy proofs, sweep lines, and dedup all\nstart with `sort`. When stuck, always ask: **\"What happens if I sort the\ndata first?\"**",
    "Các mẫu \"sắp rồi quét\"", "Sắp xếp biến dữ liệu rời rạc thành hàng xóm: hiệu kề, gộp đoạn, gán hạng.",
    "## Mẫu 1 — cặp gần nhất bằng hiệu kề\n\nSau khi sắp, hai giá trị gần nhau nhất **nằm cạnh nhau**:\n\n```cpp\nsort(a.begin(), a.end());\nlong long best = a[1] - a[0];\nfor (int i = 2; i < n; ++i) best = min(best, a[i] - a[i-1]);\n```\n\nQuét cặp O(n^2) thành O(n log n). Bước \"sắp tạo tính cục bộ\" này nuôi các\nbài hiệu nhỏ nhất, giá trị gần nhất, và khoảng cách.\n\n### Mẫu 2 — gộp đoạn\n\nSắp theo đầu đoạn, rồi kéo dài đoạn đang chạy:\n\n```cpp\nsort(iv.begin(), iv.end());            // cặp [đầu, cuối]\nvector<pair<long long,long long>> merged;\nfor (auto& [s, e] : iv) {\n    if (!merged.empty() && s <= merged.back().second)\n        merged.back().second = max(merged.back().second, e);\n    else merged.push_back({s, e});\n}\n```\n\nChú ý `<=` hay `<`: chúng quyết định đoạn chạm nhau có gộp không. Đọc đề.\n\n### Mẫu 3 — gán hạng\n\n```cpp\nsort(b.begin(), b.end());                          // bản sao đã sắp\nfor (long long x : a)\n    out << lower_bound(b.begin(), b.end(), x) - b.begin() + 1 << ' ';\n```\n\nHạng của phần tử = vị trí của nó trong bản sao đã sắp. Giá trị hòa nhận\nhạng khác nhau trừ khi bạn lọc trùng trước — một quyết định đọc đề.\n\n### Vì sao sắp mở ra mọi thứ\n\nTìm kiếm nhị phân (module sau), chứng minh tham lam, quét đường thẳng, và\nlọc trùng đều bắt đầu từ `sort`. Khi bí, luôn hỏi: **\"Sắp dữ liệu trước thì\nsao?\"**",
)
A1 = challenge("hsg-p6-min-diff", "Minimum Difference", "**Description:** Given n integers, find the minimum absolute difference\nbetween any two of them.\n\n**Input:** Line 1: n (2 <= n <= 10^5). Line 2: n integers (|a_i| <= 10^9).\n**Output:** One integer — the minimum difference.\n\n**Example:** `4` / `10 -7 3 22` -> `7` (pair 3 and 10).", [contest_test("sample", "4\n10 -7 3 22\n", "7\n", "Sorted: -7 3 10 22; adjacent diffs 10, 7, 12."), contest_test("duplicates", "3\n5 5 5\n", "0\n", "Equal values give difference 0."), contest_test("negatives", "3\n-9 -2 -5\n", "3\n", "Sorted: -9 -5 -2; diffs 4, 3."), contest_test("two elements", "2\n1000000000 -1000000000\n", "2000000000\n", "The full long long range — int overflows.")], level="imitation", difficulty="beginner")

A2 = challenge("hsg-p6-desc-median", "Descending Median", "**Description:** Given n integers, print them sorted in **descending**\norder, then print the median. For even n, the median is the lower of the\ntwo middle elements in the sorted-ascending order.\n\n**Input:** Line 1: n (1 <= n <= 10^5). Line 2: n integers (|a_i| <= 10^9).\n**Output:** Line 1: n sorted values descending, space-separated, no\ntrailing space. Line 2: the median.\n\n**Example:** `4` / `3 1 4 2` -> line 1 `4 3 2 1`, line 2 `2`.", [contest_test("sample", "4\n3 1 4 2\n", "4 3 2 1\n2\n", "Descending sort; lower middle of 1 2 3 4 is 2."), contest_test("odd count", "5\n7 1 9 3 5\n", "9 7 5 3 1\n5\n", "Odd n: exact middle element."), contest_test("single", "1\n42\n", "42\n42\n", "The element is its own median."), contest_test("all equal", "3\n6 6 6\n", "6 6 6\n6\n", "Median of equal values is that value.")], level="guided", difficulty="beginner")

A3 = challenge("hsg-p6-merge-intervals", "Merged Intervals", "**Description:** Given n intervals [l_i, r_i], merge all overlapping or\ntouching intervals and print the merged intervals sorted by start.\n\n**Input:** Line 1: n (1 <= n <= 10^5). Next n lines: l r (0 <= l <= r <= 10^9).\n**Output:** Each merged interval on its own line: `l r`.\n\n**Example:** `4` / `1 3` / `2 6` / `8 10` / `15 18` -> `1 6` / `8 10` / `15 18`.", [contest_test("sample", "4\n1 3\n2 6\n8 10\n15 18\n", "1 6\n8 10\n15 18\n", "1 3 and 2 6 touch; the rest stay separate."), contest_test("nested", "3\n1 10\n2 3\n4 5\n", "1 10\n", "Inner intervals are absorbed."), contest_test("touching", "2\n1 2\n2 3\n", "1 3\n", "Touching intervals merge (s <= current end)."), contest_test("single", "1\n5 5\n", "5 5\n", "A point interval passes through.")], level="guided", difficulty="beginner")

A4 = challenge("hsg-p6-rank", "Ranks", "**Description:** For each of n values, print its **dense rank**: the\nposition of its value in the ascending order of DISTINCT values\n(1-based). Equal values share the same rank; ranks are consecutive.\n\n**Input:** Line 1: n (1 <= n <= 10^5). Line 2: n integers (|a_i| <= 10^9).\n**Output:** n integers — the ranks in input order.\n\n**Example:** `4` / `30 10 20 10` -> `3 1 2 1` (distinct: 10 20 30).", [contest_test("sample", "4\n30 10 20 10\n", "3 1 2 1\n", "Dense ranks: distinct values 10 20 30; tied 10s share rank 1."), contest_test("distinct", "3\n5 1 9\n", "2 1 3\n", "Distinct values, direct positions."), contest_test("all equal", "4\n7 7 7 7\n", "1 1 1 1\n", "All ties; everyone shares rank 1."), contest_test("reverse", "4\n4 3 2 1\n", "4 3 2 1\n", "Ranks mirror the input.")], level="independent", difficulty="intermediate")

A5 = challenge("hsg-p6-scoreboard", "Scoreboard", "**Description:** A contest has n participants, each with a score. Print\nparticipants in **descending score order; ties keep input order** — and\nfor each, print `name score`.\n\n**Input:** Line 1: n (1 <= n <= 10^5). Next n lines: name (single word,\n<= 20 chars) and score s (0 <= s <= 10^9).\n**Output:** n lines: `name score`, scoreboard order.\n\n**Example:** `3` / `trang 50` / `binh 80` / `an 50` -> `binh 80` /\n`trang 50` / `an 50` (trang before an: input order).", [contest_test("sample", "3\ntrang 50\nbinh 80\nan 50\n", "binh 80\ntrang 50\nan 50\n", "Tie 50: trang entered first."), contest_test("reverse input", "3\nzz 10\nyy 20\nxx 30\n", "xx 30\nyy 20\nzz 10\n", "Distinct scores, sorted descending."), contest_test("all tie", "3\nnam 5\nanh 5\nbinh 5\n", "nam 5\nanh 5\nbinh 5\n", "Full tie keeps input order exactly."), contest_test("max score ties", "2\nhai 1000000000\nduc 1000000000\n", "hai 1000000000\nduc 1000000000\n", "Max scores tie — input order.")], level="combination", difficulty="intermediate")

write_practice(
    M, "hsg-p6-sorting", "Sorting Set", "Five sorting problems: adjacent-difference sweep, descending median, interval merge, dense ranks, and a stable scoreboard.",
    "Bộ đề sắp xếp", "Năm bài sắp xếp: quét hiệu kề, trung vị giảm dần, gộp đoạn, hạng đậm đặc, và bảng điểm ổn định.",
    "hsg-m6-sweep", 65, "beginner",
    [A1, A2, A3, A4, A5],
    {
        "hsg-p6-min-diff": vi_challenge("Hiệu nhỏ nhất", "**Mô tả:** Cho n số nguyên, tìm hiệu tuyệt đối nhỏ nhất giữa hai số bất kỳ.\n\n**Dữ liệu vào:** Dòng 1: n (2 <= n <= 10^5). Dòng 2: n số (|a_i| <= 10^9).\n**Dữ liệu ra:** Một số nguyên.\n\n**Ví dụ:** `4` / `10 -7 3 22` -> `7` (cặp 3 và 10).", [("ví dụ đề bài", "Đã sắp: -7 3 10 22; các hiệu kề 10, 7, 12."), ("có trùng", "Hai số bằng nhau cho hiệu 0."), ("toàn âm", "Đã sắp: -9 -5 -2; hiệu 4, 3."), ("hai phần tử", "Cả miền long long — int sẽ tràn.")]),
        "hsg-p6-desc-median": vi_challenge("Trung vị giảm dần", "**Mô tả:** Cho n số nguyên, in chúng theo thứ tự **giảm dần** (không có khoảng trắng thừa cuối dòng), rồi in trung vị. Với n chẵn, trung vị là phần tử giữa **thấp hơn** trong thứ tự tăng dần.\n\n**Dữ liệu vào:** Dòng 1: n. Dòng 2: n số (|a_i| <= 10^9).\n**Dữ liệu ra:** Dòng 1: n số giảm dần. Dòng 2: trung vị.\n\n**Ví dụ:** `4` / `3 1 4 2` -> dòng 1 `4 3 2 1`, dòng 2 `2`.", [("ví dụ đề bài", "Sắp giảm; giữa dưới của 1 2 3 4 là 2."), ("lẻ", "n lẻ: đúng phần tử giữa."), ("một phần tử", "Phần tử là trung vị của chính nó."), ("bằng nhau", "Trung vị của các số bằng nhau là số đó.")]),
        "hsg-p6-merge-intervals": vi_challenge("Gộp đoạn", "**Mô tả:** Cho n đoạn [l_i, r_i], gộp các đoạn chồng lấn hoặc chạm nhau và in kết quả theo đầu đoạn tăng dần.\n\n**Dữ liệu vào:** Dòng 1: n. n dòng: l r (0 <= l <= r <= 10^9).\n**Dữ liệu ra:** Mỗi đoạn đã gộp một dòng: `l r`.\n\n**Ví dụ:** `4` / `1 3` / `2 6` / `8 10` / `15 18` -> `1 6` / `8 10` / `15 18`.", [("ví dụ đề bài", "1 3 chạm 2 6; còn lại đứng riêng."), ("lồng nhau", "Các đoạn trong bị hấp thụ."), ("chạm nhau", "Đoạn chạm nhau được gộp (s <= cuối hiện tại)."), ("một đoạn", "Đoạn điểm đi qua nguyên vẹn.")]),
        "hsg-p6-rank": vi_challenge("Hạng đậm đặc", "**Mô tả:** Với mỗi giá trị trong n giá trị, in **hạng đậm đặc**: vị trí của giá trị đó trong thứ tự tăng dần của CÁC GIÁ TRỊ PHÂN BIỆT (1-based). Giá trị bằng nhau dùng chung một hạng; các hạng liên tiếp.\n\n**Dữ liệu vào:** Dòng 1: n. Dòng 2: n số (|a_i| <= 10^9).\n**Dữ liệu ra:** n số theo thứ tự nhập.\n\n**Ví dụ:** `4` / `30 10 20 10` -> `3 1 2 1` (phân biệt: 10 20 30).", [("ví dụ đề bài", "Hai số 10 hòa chung hạng 1; 20 hạng 2; 30 hạng 3."), ("phân biệt", "Giá trị khác nhau, vị trí trực tiếp."), ("toàn bằng", "Tất cả hòa; ai cũng hạng 1."), ("đảo ngược", "Hạng soi ngược đầu vào.")]),
        "hsg-p6-scoreboard": vi_challenge("Bảng điểm", "**Mô tả:** Một kỳ thi có n thí sinh với điểm số. In danh sách theo điểm **giảm dần; hòa giữ thứ tự nhập** — mỗi dòng `ten diem`.\n\n**Dữ liệu vào:** Dòng 1: n. n dòng: tên (một từ, <= 20 ký tự) và điểm s (0 <= s <= 10^9).\n**Dữ liệu ra:** n dòng `ten diem`.\n\n**Ví dụ:** `3` / `trang 50` / `binh 80` / `an 50` -> `binh 80` / `trang 50` / `an 50` (trang trước an: thứ tự nhập).", [("ví dụ đề bài", "Hòa 50: trang nhập trước."), ("đầu vào đảo", "Điểm phân biệt, sắp giảm dần."), ("toàn hòa", "Hòa hoàn toàn giữ nguyên thứ tự nhập."), ("hòa điểm tối đa", "Điểm tối đa hòa nhau — theo thứ tự nhập.")]),
    },
    solutions=[
        ("hsg-p6-min-diff", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> a(n);\n    for (long long& x : a) in >> x;\n    sort(a.begin(), a.end());\n    long long best = a[1] - a[0];\n    for (int i = 2; i < n; ++i) best = min(best, a[i] - a[i-1]);\n    out << best << \"\\n\";\n}", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> a(n);\n    for (long long& x : a) in >> x;\n    sort(a.begin(), a.end());\n    // near-miss: initializes the running best to 0 — the true minimum\n    // adjacent difference can never be compared fairly against 0 when it\n    // is positive, so distinct positive values report 0 instead\n    long long best = 0;\n    for (int i = 1; i < n; ++i) best = min(best, a[i] - a[i-1]);\n    out << best << \"\\n\";\n}"),
        ("hsg-p6-desc-median", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> a(n);\n    for (long long& x : a) in >> x;\n    vector<long long> asc = a;\n    sort(asc.begin(), asc.end());\n    sort(a.begin(), a.end(), greater<long long>());\n    for (int i = 0; i < n; ++i) out << a[i] << (i + 1 < n ? \" \" : \"\\n\");\n    out << asc[(n - 1) / 2] << \"\\n\";\n}", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> a(n);\n    for (long long& x : a) in >> x;\n    sort(a.begin(), a.end(), greater<long long>());\n    // near-miss: prints a trailing space after the last value —\n    // byte-exact contest output rejects that as wrong format\n    for (int i = 0; i < n; ++i) out << a[i] << (i + 1 < n ? \" \" : \" \");\n    out << a[n / 2] << \"\\n\";\n}"),
        ("hsg-p6-merge-intervals", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<pair<long long,long long>> iv(n);\n    for (auto& p : iv) in >> p.first >> p.second;\n    sort(iv.begin(), iv.end());\n    vector<pair<long long,long long>> merged;\n    for (auto& p : iv) {\n        if (!merged.empty() && p.first <= merged.back().second)\n            merged.back().second = max(merged.back().second, p.second);\n        else merged.push_back(p);\n    }\n    for (auto& p : merged) out << p.first << \" \" << p.second << \"\\n\";\n}", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<pair<long long,long long>> iv(n);\n    for (auto& p : iv) in >> p.first >> p.second;\n    sort(iv.begin(), iv.end());\n    vector<pair<long long,long long>> merged;\n    for (auto& p : iv) {\n        // near-miss: < instead of <= — touching intervals (next start\n        // equals current end) stay separate, violating the merge contract\n        if (!merged.empty() && p.first < merged.back().second)\n            merged.back().second = max(merged.back().second, p.second);\n        else merged.push_back(p);\n    }\n    for (auto& p : merged) out << p.first << \" \" << p.second << \"\\n\";\n}"),
        ("hsg-p6-rank", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> a(n);\n    for (long long& x : a) in >> x;\n    vector<long long> b = a;\n    sort(b.begin(), b.end());\n    b.erase(unique(b.begin(), b.end()), b.end());\n    for (int i = 0; i < n; ++i) {\n        int r = int(lower_bound(b.begin(), b.end(), a[i]) - b.begin()) + 1;\n        out << r << (i + 1 < n ? \" \" : \"\\n\");\n    }\n}", "#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> a(n);\n    for (long long& x : a) in >> x;\n    vector<long long> b = a;\n    sort(b.begin(), b.end());\n    // near-miss: no dedup — tied values skip positions, so the second 10\n    // gets rank 2 instead of sharing rank 1 (dense-tie contract broken)\n    for (int i = 0; i < n; ++i) {\n        int r = int(lower_bound(b.begin(), b.end(), a[i]) - b.begin()) + 1;\n        out << r << (i + 1 < n ? \" \" : \"\\n\");\n    }\n}"),
        ("hsg-p6-scoreboard", "#include <iostream>\n#include <algorithm>\n#include <string>\n#include <vector>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<pair<int,string>> v(n);\n    for (auto& p : v) in >> p.second >> p.first;\n    stable_sort(v.begin(), v.end(), [](const pair<int,string>& a, const pair<int,string>& b) {\n        return a.first > b.first;\n    });\n    for (auto& p : v) out << p.second << \" \" << p.first << \"\\n\";\n}", "#include <iostream>\n#include <algorithm>\n#include <string>\n#include <vector>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<pair<int,string>> v(n);\n    for (auto& p : v) in >> p.second >> p.first;\n    // near-miss: breaks score ties ALPHABETICALLY by name — the contract\n    // requires ties to keep input order, silently violated here\n    stable_sort(v.begin(), v.end(), [](const pair<int,string>& a, const pair<int,string>& b) {\n        return a.first > b.first || (a.first == b.first && a.second < b.second);\n    });\n    for (auto& p : v) out << p.second << \" \" << p.first << \"\\n\";\n}"),
    ],
)
write_checkpoint(
    M, "hsg-cp-m6", "Checkpoint — Sorting", "Pass the graded problem to finish the sorting module.", 15,
    "**Checkpoint — sorting.** Pass the graded challenge below to finish the module.",
    "Checkpoint — sắp xếp", "Vượt qua bài chấm cuối module để hoàn thành phần sắp xếp.",
    "**Checkpoint — sắp xếp.** Vượt qua challenge có chấm bên dưới để hoàn thành module.",
    challenge("hsg-cp-m6-tower", "Tower Heights", "**Description:** A skyline has n towers with heights h_1..h_n. In one\nsecond you may pick any tower and change its height by 1. Find the\n**minimum total seconds** to make all towers equal, and print the common\nheight achieving it. If several heights achieve the same minimum, print\nthe smallest one.\n\n**Input:** Line 1: n (1 <= n <= 10^5). Line 2: n heights (0 <= h_i <= 10^9).\n**Output:** Line 1: minimum total change. Line 2: the optimal height\n(smallest if several tie).\n\n**Example:** `3` / `1 2 4` -> the median 2 gives 1+0+2 = 3 seconds;\nheight 3 also gives 3, so print the smaller: `2`.", [contest_test("sample", "3\n1 2 4\n", "3\n2\n", "Median minimizes sum of absolute differences; tie 2 vs 3, smaller wins."), contest_test("single", "1\n999999999\n", "0\n999999999\n", "Already equal — zero moves."), contest_test("even tie", "4\n1 2 100 101\n", "198\n2\n", "Every height in [2, 100] ties at 198; the smallest is 2."), contest_test("equal towers", "3\n7 7 7\n", "0\n7\n", "No change needed.")], level="guided", difficulty="intermediate")
    ,
    vi_challenge("Chiều cao tháp", "**Mô tả:** Một đường chân trời có n tháp với chiều cao h_1..h_n. Mỗi giây bạn có thể chọn một tháp và đổi chiều cao đi 1. Tìm **tổng giây tối thiểu** để mọi tháp bằng nhau, và in chiều cao chung đạt được (nếu nhiều chiều cao cùng đạt minimum, in số nhỏ nhất).\n\n**Dữ liệu vào:** Dòng 1: n. Dòng 2: n chiều cao (0 <= h_i <= 10^9).\n**Dữ liệu ra:** Dòng 1: tổng thay đổi tối thiểu. Dòng 2: chiều cao tối ưu (nhỏ nhất nếu hòa).\n\n**Ví dụ:** `3` / `1 2 4` -> trung vị 2 cho 1+0+2 = 3 giây; chiều cao 3 cũng cho 3, in số nhỏ hơn: `2`.", [("ví dụ đề bài", "Trung vị cực tiểu hóa tổng |lệch|; hòa 2 với 3, chọn số nhỏ."), ("một tháp", "Đã bằng nhau — không di chuyển."), ("n chẵn hòa", "Mọi chiều cao trong [2, 100] hòa ở 198; nhỏ nhất là 2."), ("tháp bằng nhau", "Không cần thay đổi.")]),
    solution="#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> h(n);\n    for (long long& x : h) in >> x;\n    sort(h.begin(), h.end());\n    // candidates: lower median and upper median — evaluate both\n    long long m1 = h[(n - 1) / 2], m2 = h[n / 2];\n    auto cost = [&](long long t) {\n        long long c = 0;\n        for (long long x : h) c += llabs(x - t);\n        return c;\n    };\n    long long c1 = cost(m1), c2 = cost(m2);\n    // smallest optimal height: for odd n it is m1; for even n every height\n    // in [m1, m2] ties, so m1 is the smallest — its cost equals c2\n    long long bestH = m1, bestC = min(c1, c2);\n    out << bestC << \"\\n\" << bestH << \"\\n\";\n}",
    wrong="#include <iostream>\n#include <algorithm>\nusing namespace std;\nvoid solve(std::istream& in, std::ostream& out) {\n    int n; in >> n;\n    vector<long long> h(n);\n    for (long long& x : h) in >> x;\n    sort(h.begin(), h.end());\n    // near-miss: centers on the MEAN — the mean minimizes squared error,\n    // not the sum of absolute differences; the reported height is wrong\n    // on every even-n tie and on skewed inputs\n    long long sum = 0;\n    for (long long x : h) sum += x;\n    long long t = sum / n;\n    long long c = 0;\n    for (long long x : h) c += llabs(x - t);\n    out << c << \"\\n\" << t << \"\\n\";\n}",
)

print("M6 done")
