#!/usr/bin/env node
/**
 * Generate src/lib/curriculum/mdx-map.ts from the curriculum content tree.
 *
 * Every lesson body must be statically imported (decision D-14: the bundler
 * compiles content MDX at build time; no runtime compilation). The map was
 * handwritten when the curriculum had one module; generated now so content
 * and code cannot drift. Keys are `<moduleId>/<lessonId>.mdx`, matching each
 * lesson JSON's contentPath suffix (./<lessonId>.mdx).
 *
 * Run via `pnpm content:map` (wired into prebuild and predev).
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const TRACKS_ROOT = path.join(process.cwd(), "src", "content", "tracks");
const OUT_FILE = path.join(process.cwd(), "src", "lib", "curriculum", "mdx-map.ts");

/** lessonId -> PascalCase React component name (digit-safe, deduped later). */
function componentName(lessonId) {
  const pascal = lessonId
    .split("-")
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("")
    .replace(/^(\d)/, "L$1");
  return pascal || "Lesson";
}

/**
 * Walk a module dir; every `<lessonId>.mdx` beside a `<lessonId>/` challenges
 * dir (or simply referenced by module.json) becomes one import. Only MDX that
 * module.json references is mapped, so orphan files never enter the build.
 */
function collectModule(moduleDir, moduleId, out) {
  const moduleJsonPath = path.join(moduleDir, "module.json");
  if (!existsSync(moduleJsonPath)) return;
  const moduleJson = JSON.parse(readFileSync(moduleJsonPath, "utf8"));
  for (const ref of moduleJson.lessons ?? []) {
    const lessonId = ref.reference;
    const mdxPath = path.join(moduleDir, "lessons", `${lessonId}.mdx`);
    if (!existsSync(mdxPath)) continue;
    // Import path relative to src/ (the "@/" alias root).
    const relFromSrc = path
      .relative(path.join(process.cwd(), "src"), mdxPath)
      .split(path.sep)
      .join("/");
    out.push({ key: `${moduleId}/${lessonId}.mdx`, relFromSrc, lessonId });
    // Vietnamese sidecar beside the English body, when it exists.
    const viPath = path.join(moduleDir, "lessons", `${lessonId}.vi.mdx`);
    if (existsSync(viPath)) {
      const viRelFromSrc = path
        .relative(path.join(process.cwd(), "src"), viPath)
        .split(path.sep)
        .join("/");
      out.push({
        key: `${moduleId}/${lessonId}.vi.mdx`,
        relFromSrc: viRelFromSrc,
        lessonId,
      });
    }
  }
}

function main() {
  const lessons = [];
  for (const track of readdirSync(TRACKS_ROOT).sort()) {
    const trackDir = path.join(TRACKS_ROOT, track);
    if (!statSync(trackDir).isDirectory()) continue;
    const coursesDir = path.join(trackDir, "courses");
    if (!existsSync(coursesDir)) continue;
    for (const course of readdirSync(coursesDir).sort()) {
      const modulesDir = path.join(coursesDir, course, "modules");
      if (!existsSync(modulesDir)) continue;
      for (const moduleId of readdirSync(modulesDir).sort()) {
        const moduleDir = path.join(modulesDir, moduleId);
        if (statSync(moduleDir).isDirectory()) collectModule(moduleDir, moduleId, lessons);
      }
    }
  }

  if (lessons.length === 0) {
    throw new Error("generate-mdx-map: no referenced lesson MDX found under src/content/tracks");
  }

  const used = new Set();
  const imports = [];
  const entries = [];
  for (const lesson of lessons) {
    // vi sidecar entries arrive as their own items (key ends in .vi.mdx).
    const isVi = lesson.key.endsWith(".vi.mdx");
    let name = componentName(lesson.lessonId) + (isVi ? "Vi" : "");
    while (used.has(name)) name += "_";
    used.add(name);
    imports.push(`import ${name} from "@/${lesson.relFromSrc}";`);
    entries.push(`  ["${lesson.key}"]: ${name},`);
  }

  const file = `import type { ComponentType } from "react";

/**
 * Static MDX import map (decision D-14). Keys are \`<moduleId>/<lessonId>.mdx\`
 * — matching each lesson JSON's contentPath suffix. The bundler compiles
 * content MDX at build time; no runtime compilation.
 *
 * GENERATED by scripts/generate-mdx-map.mjs — do not edit by hand.
 * Regenerate with \`pnpm content:map\` (runs automatically prebuild/predev).
 */
export type MdxComponent = ComponentType<Record<string, unknown>>;

${imports.sort().join("\n")}

export const mdxMap: Record<string, MdxComponent> = {
${entries.join("\n")}
};

export function getLessonMdx(
  contentPath: string,
  locale = "en",
): MdxComponent | undefined {
  // contentPath is "./<lessonId>.mdx" relative to the lesson JSON; the map
  // key is "<moduleId>/<lessonId>.mdx" (or "<moduleId>/<lessonId>.vi.mdx"
  // for the Vietnamese sidecar). Fall back to the bare filename for legacy
  // single-module content, and to English when no sidecar exists.
  const suffix = locale === "en" ? ".mdx" : ".vi.mdx";
  const normalized = contentPath.replace(/^\\.\\//, "").replace(/\.mdx$/, suffix);
  if (mdxMap[normalized]) return mdxMap[normalized];
  const fileName = normalized.split("/").pop() ?? normalized;
  const byName = mdxMap[Object.keys(mdxMap).find((key) => key.endsWith("/" + fileName)) ?? ""];
  if (byName) return byName;
  // Missing vi sidecar → render the English component (matches the loader's
  // English body fallback, so a partially translated course still renders).
  if (locale !== "en") return getLessonMdx(contentPath, "en");
  return undefined;
}
`;

  writeFileSync(OUT_FILE, file);
  console.log(
    `[generate-mdx-map] wrote ${lessons.length} lesson imports -> src/lib/curriculum/mdx-map.ts`,
  );
}

main();
